services:
  web:
    build: .
    command: >
      bash -c "
      echo '=== ENV VARS ===' &&
      printenv &&
      echo '================' &&
      python manage.py migrate --noinput &&
      python manage.py runserver 0.0.0.0:8000 --noreload
      "
    volumes:
      - ./task_manager:/app
      - ./task_manager/static:/app/static
      - ./temp_db:/app/temp_db
    environment:
      # Основные настройки Django
      - SECRET_KEY=django-insecuretestTEST
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=task_manager.settings
      - IS_DOCKER=True
      - DJANGO_ALLOW_ASYNC_UNSAFE=True
      - OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES

      # Настройки базы данных
      - SQLITE_DB_PATH=/app/temp_db/db.sqlite3

      # Настройки API
      - INTERNAL_API_URL=http://web:8000/api/
      - EXTERNAL_API_URL=http://localhost:8000/api/

      # Настройки Telegram
      - TELEGRAM_TOKEN=7909971973:AAEXyUOaj09Ms_nMK_onJe46crZyDO4n4Zg
      - API_REQUEST_TIMEOUT=10

      # Настройки времени
      - TIME_ZONE=Europe/Moscow
      - CELERY_TIMEZONE=Europe/Moscow

      # Настройки Celery
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

      # Технические настройки
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - backend

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - backend

  celery:
    build: .
    command: >
      bash -c "
      echo 'Waiting for Redis...' &&
      while ! nc -z redis 6379; do sleep 1; done &&
      echo 'Starting Celery worker...' &&
      celery -A task_manager worker --loglevel=info 
      "
    environment:
      - SECRET_KEY=django-insecuretestTEST
      - DJANGO_SETTINGS_MODULE=task_manager.settings
      - IS_DOCKER=True
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - SQLITE_DB_PATH=/app/temp_db/db.sqlite3
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
      - web
    networks:
      - backend
    restart: unless-stopped

  celery-beat:
    build: .
    command: >
      bash -c "
      while ! nc -z redis 6379; do sleep 1; done &&
      python manage.py migrate django_celery_beat &&
      celery -A task_manager beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
      "
    environment:
      - SECRET_KEY=django-insecuretestTEST
      - DJANGO_SETTINGS_MODULE=task_manager.settings
      - IS_DOCKER=True
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - SQLITE_DB_PATH=/app/temp_db/db.sqlite3
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
      - web
    networks:
      - backend
    restart: unless-stopped

  bot:
    build: .
    command: python telegram_bot/cli.py
    environment:
      - SECRET_KEY=django-insecuretestTEST
      - DJANGO_SETTINGS_MODULE=task_manager.settings
      - IS_DOCKER=True
      - INTERNAL_API_URL=http://web:8000/api/
      - TELEGRAM_TOKEN=7909971973:AAEXyUOaj09Ms_nMK_onJe46crZyDO4n4Zg
      - SQLITE_DB_PATH=/app/temp_db/db.sqlite3
    depends_on:
      - web
      - redis
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge